from TDA import *
from exportaciones import *


ls1 = ListaCircularDoblementeEnlazada()
ls1.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls1.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls1.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")

ls2 = ListaCircularDoblementeEnlazada()
ls2.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls2.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls2.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")
ls2.agregar_al_final("Cancion4","Artista4","Album4","imagen4","ruta4")
ls2.agregar_al_final("Cancion5","Artista5","Album5","imagen5","ruta5")

ls3 = ListaCircularDoblementeEnlazada()
ls3.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls3.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls3.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")
ls3.agregar_al_final("Cancion4","Artista4","Album4","imagen4","ruta4")
ls3.agregar_al_final("Cancion5","Artista5","Album5","imagen5","ruta5")
ls3.agregar_al_final("Cancion6","Artista6","Album6","imagen6","ruta6")
ls3.agregar_al_final("Cancion7","Artista7","Album7","imagen7","ruta7")

ls4 = ListaCircularDoblementeEnlazada()
ls4.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls4.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls4.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")
ls4.agregar_al_final("Cancion4","Artista4","Album4","imagen4","ruta4")
ls4.agregar_al_final("Cancion5","Artista5","Album5","imagen5","ruta5")
ls4.agregar_al_final("Cancion6","Artista6","Album6","imagen6","ruta6")
ls4.agregar_al_final("Cancion7","Artista7","Album7","imagen7","ruta7")
ls4.agregar_al_final("Cancion8","Artista8","Album8","imagen8","ruta8")
ls4.agregar_al_final("Cancion9","Artista9","Album9","imagen9","ruta9")

ls5 = ListaCircularDoblementeEnlazada()
ls5.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls5.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls5.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")
ls5.agregar_al_final("Cancion4","Artista4","Album4","imagen4","ruta4")
ls5.agregar_al_final("Cancion5","Artista5","Album5","imagen5","ruta5")
ls5.agregar_al_final("Cancion6","Artista6","Album6","imagen6","ruta6")
ls5.agregar_al_final("Cancion7","Artista7","Album7","imagen7","ruta7")
ls5.agregar_al_final("Cancion8","Artista8","Album8","imagen8","ruta8")
ls5.agregar_al_final("Cancion9","Artista9","Album9","imagen9","ruta9")
ls5.agregar_al_final("Cancion10","Artista10","Album10","imagen10","ruta10")
ls5.agregar_al_final("Cancion11","Artista11","Album11","imagen11","ruta11")

ls6 = ListaCircularDoblementeEnlazada()
ls6.agregar_al_final("Cancion1","Artista1","Album1","imagen1","ruta1")
ls6.agregar_al_final("Cancion2","Artista2","Album2","imagen2","ruta2")
ls6.agregar_al_final("Cancion3","Artista3","Album3","imagen3","ruta3")
ls6.agregar_al_final("Cancion4","Artista4","Album4","imagen4","ruta4")
ls6.agregar_al_final("Cancion5","Artista5","Album5","imagen5","ruta5")
ls6.agregar_al_final("Cancion6","Artista6","Album6","imagen6","ruta6")
ls6.agregar_al_final("Cancion7","Artista7","Album7","imagen7","ruta7")
ls6.agregar_al_final("Cancion8","Artista8","Album8","imagen8","ruta8")
ls6.agregar_al_final("Cancion9","Artista9","Album9","imagen9","ruta9")
ls6.agregar_al_final("Cancion10","Artista10","Album10","imagen10","ruta10")
ls6.agregar_al_final("Cancion11","Artista11","Album11","imagen11","ruta11")
ls6.agregar_al_final("Cancion12","Artista12","Album12","imagen12","ruta12")
ls6.agregar_al_final("Cancion13","Artista13","Album13","imagen13","ruta13")
ls6.agregar_al_final("Cancion14","Artista14","Album14","imagen14","ruta14")
ls6.agregar_al_final("Cancion15","Artista15","Album15","imagen15","ruta15")

listadoPlaylist = ListaCircularDoblementeEnlazada()
listadoPlaylist.agregar_al_final_playlist("Playlist1",ls1)
listadoPlaylist.agregar_al_final_playlist("Playlist2",ls2)
listadoPlaylist.agregar_al_final_playlist("Playlist3",ls3)
listadoPlaylist.agregar_al_final_playlist("Playlist4",ls4)
listadoPlaylist.agregar_al_final_playlist("Playlist5",ls5)
listadoPlaylist.agregar_al_final_playlist("Playlist6",ls6)
# listadoPlaylist.imprimir_playlist()
#ls1.imprimir_lista()
'''listadoPrueba.linkearIndices()
for i in range (listadoPrueba.tamanio):
    data = listadoPrueba.obtenerNodoIndex(i)
    print(data.dato.nombre, data.identificador)'''

prueba().leer_xml("entrada.xml")
exportarHTML(blb)
#exportarHTML(ls6)