# diccioario de palabras clave

reservadas = {
    # elementos externos
    'INICIO'               :   'Inicio',
    'ENCABEZADO'           :   'Encabezado',
    'CUERPO'               :   'Cuerpo',
    # Elementos medios
    'TITULOPAGINA'         :   'TituloPagina',
    'TITULO'               :   'Titulo',
    'FONDO'                :   'Fondo',
    'PARRAFO'              :   'Parrafo',
    'TEXTO'                :   'Texto',
    'CODIGO'               :   'Codigo',
    'SALTO'                :   'Salto',
    'TABLA'                :   'Tabla',
    'NEGRITA'              :   'Negrita',
    'CURSIVA'              :   'Cursiva',
    'TACHADO'              :   'Tachado',
    'SUBRAYADO'            :   'Subrayado',
    # elementos internos
    'texto'                :   'texto',
    'POSICION'             :   'posicion',
    'TAMAÃ±O'               :   'tamaÃ±o',
    'COLOR'                :   'color',
    'FUENTE'               :   'fuente',
    'FILAS'              :   'filas',
    'COLUMNAS'           :   'columnas',
    'FILA'               :   'fila',
    'COLUMNA'            :   'columna',
    'ELEMENTO'             :   'elemento',
    'CANTIDAD'             :    'cantidad',
    # signos
    '"'                   :   '"',
    ';'                   :   ';',
    ':'                   :   ':',
    '{'                  :   '{',
    '}'                  :   '}',
    '['                   :   '[',
    ']'                   :   ']',
    ','                   :   ','
}

traduccion = {
    'TITULO'               :   'h',
    'FONDO'                :   'body',
    'PARRAFO'              :   'p',
    'TEXTO'                :   'p',
    'CODIGO'               :   'code',
    'SALTO'                :   'br',
    'TABLA'                :   'table',
    'NEGRITA'              :   'br',
    'CURSIVA'              :   'i',
    'TACHADO'              :   'del',
    'SUBRAYADO'            :   'u',
    # elementos internos
    'POSICION'             :   'align',
    'TAMAÃ±O'               :   'size',
    'COLOR'                :   'color',
    'FUENTE'               :   'font',
    'IZQUIERDA'           :   'left',
    'CENTRO'              :   'center',
    'DERECHA'             :   'right',
    'AZUL'         :   'blue',
    'ROJO'         :   'red',
    'AMARILLO'        :   'yellow',
    'BLANCO'        :   'white',
    # elementos de tabla
    'FILA'               :   'row',
    'COLUMNA'            :   'column',
    'ELEMENTO'             :   'elemento',
    'CANTIDAD'             :    'cantidad',
    'FILAS'              :   'filas',
    'COLUMNAS'           :   'columnas',
}